<?php
/* First-pass native adapters for the uploaded legacy Three.js PHP scenes. Art History is deliberately untouched. */
$html = file_get_contents(__DIR__ . '/index.php');
$insert = <<<'JS'
function sourceReturn(){const r=new THREE.Mesh(new THREE.OctahedronGeometry(.75,0),mats.glow);r.position.set(0,1.25,7);root.add(r);clickObj(r,'Return','Back to the altar.',buildMain);animated.push({object:r,speed:.7})}
function sourceShell(room,w=24,d=24,h=10,bg=0x050505){reset();state.room='source';scene.background=new THREE.Color(bg);scene.fog=new THREE.FogExp2(bg,.012);setSpawn(room.spawn?.x??0,room.spawn?.z??8,room.spawn?.yaw??180);box(0,-.05,0,w,.1,d,mats.floor,false);sourceReturn();return (sceneData.media?.[room.category]||[])}
function sourceImagePlane(item,w,h){return new THREE.Mesh(new THREE.PlaneGeometry(w,h),item?new THREE.MeshBasicMaterial({map:tex(item.url),side:THREE.DoubleSide}):mats.dark)}
function buildDomeSource(room){const media=sourceShell(room,32,32,12,0x020204).filter(x=>x.type==='image'),c=room.config||{},rad=c.radius||10,count=Math.min(media.length,c.maxImages||40);const dome=new THREE.Mesh(new THREE.SphereGeometry(rad+4,32,16,0,Math.PI*2,0,Math.PI/2),new THREE.MeshStandardMaterial({color:0x090912,side:THREE.BackSide,roughness:.95}));dome.position.y=.1;root.add(dome);for(let i=0;i<count;i++){const a=i/count*Math.PI*2,y=2+(i%4)*1.65,r=rad-(i%3)*.8,p=sourceImagePlane(media[i],c.imageWidth||2.6,c.imageHeight||2);p.position.set(Math.sin(a)*r,y,Math.cos(a)*r);p.lookAt(0,y,0);root.add(p)}addLight(new THREE.PointLight(0xa9c8ff,c.lightIntensity||2.4,35,2)).position.set(0,6,0);stats.textContent=`${room.title} · ${count} floating works`;msg.textContent='A viewing dais beneath the image dome.'}
function buildObservatorySource(room){const media=sourceShell(room,30,30,12,0x000006).filter(x=>x.type==='image'),c=room.config||{};const sky=new THREE.Mesh(new THREE.SphereGeometry(c.radius||13,32,20),new THREE.MeshBasicMaterial({color:0x02020c,side:THREE.BackSide}));sky.position.y=4;root.add(sky);media.slice(0,c.maxConstellations||24).forEach((it,i)=>{const a=i/Math.max(1,media.length)*Math.PI*2,p=sourceImagePlane(it,c.panelSize||2.4,c.panelSize||2.4);p.position.set(Math.sin(a)*10,2+(i%5)*1.45,Math.cos(a)*10);p.lookAt(0,3,0);root.add(p)});for(let i=0;i<(c.starCount||220);i++){const s=new THREE.Mesh(new THREE.SphereGeometry(.025,5,5),mats.glow),a=Math.random()*Math.PI*2,r=5+Math.random()*8;s.position.set(Math.sin(a)*r,1+Math.random()*9,Math.cos(a)*r);root.add(s)}addLight(new THREE.PointLight(0x789cff,1.5,25,2)).position.set(0,5,0);stats.textContent=`${room.title} · star vault`;msg.textContent='Constellations hang inside the observatory vault.'}
function buildBooksSource(room){const media=sourceShell(room,26,28,9,0x080503).filter(x=>x.type==='image'),c=room.config||{},n=Math.min(media.length,c.maxBooks||48);box(0,4.2,-12.5,24,8,.4,mats.wood,true);for(let row=0;row<4;row++){box(0,1+row*1.75,-11.9,22,.14,.7,mats.wood,true)}for(let i=0;i<n;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(.32,.95,.55),new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL((i*.071)%1,.35,.28),roughness:.8}));b.position.set((i%16-7.5)*.62,1.55+Math.floor(i/16)*1.75,-11.45);root.add(b);clickObj(b,media[i].title,'A volume from the Books scene.',()=>{msg.textContent=media[i].title})}addLight(new THREE.PointLight(0xffc06a,2.8,25,2)).position.set(0,5,1);stats.textContent=`${room.title} · ${n} volumes`;msg.textContent='The legacy book wall has become a walkable library.'}
function buildObjectsSource(room){const media=sourceShell(room,30,30,10,0x050505).filter(x=>x.type==='image'),c=room.config||{},n=Math.min(media.length,c.maxObjects||24),rad=c.radius||8;for(let i=0;i<n;i++){const a=i/n*Math.PI*2,g=new THREE.Group();g.position.set(Math.sin(a)*rad,1.4,Math.cos(a)*rad);root.add(g);cyl(0,-.7,0,.65,1.1,mats.stone,false,g);const p=sourceImagePlane(media[i],c.objectWidth||2.1,c.objectHeight||2.1);p.position.y=.8;p.lookAt(-g.position.x,.8,-g.position.z);g.add(p)}addLight(new THREE.PointLight(0xffffff,c.lightIntensity||3,30,2)).position.set(0,6,0);stats.textContent=`${room.title} · ${n} reliquaries`;msg.textContent='Objects orbit the central reliquary floor.'}
function buildCloudsSource(room){const media=sourceShell(room,28,24,9,0xb8d8ee).filter(x=>x.type==='image'),c=room.config||{};scene.fog=new THREE.FogExp2(0xb8d8ee,.006);box(0,4,-11,26,8,.35,mats.white,true);const n=Math.min(media.length,c.maxClouds||18);for(let i=0;i<n;i++){const p=sourceImagePlane(media[i],c.cloudWidth||4,c.cloudHeight||2.5);p.position.set((i%6-2.5)*4.2,2+Math.floor(i/6)*2.1,-10.75);root.add(p)}addLight(new THREE.HemisphereLight(0xffffff,0x7890aa,1.7));stats.textContent=`${room.title} · ${n} cloud panes`;msg.textContent='A domestic room opens into a wall of moving weather.'}
function buildClockSource(room){sourceShell(room,24,24,9,0x030303);const c=room.config||{},rad=c.radius||6;const ring=new THREE.Mesh(new THREE.TorusGeometry(rad,.18,12,96),mats.gold);ring.position.y=4;root.add(ring);for(let i=0;i<12;i++){const a=i/12*Math.PI*2,s=new THREE.Mesh(new THREE.BoxGeometry(.12,.5,.12),mats.glow);s.position.set(Math.sin(a)*rad,4+Math.cos(a)*rad,0);root.add(s)}const hand=new THREE.Mesh(new THREE.BoxGeometry(.12,rad*.85,.12),mats.glow);hand.geometry.translate(0,rad*.42,0);hand.position.set(0,4,0);root.add(hand);animated.push({object:hand,speed:c.handSpeed||-.12});addLight(new THREE.PointLight(0xffd477,2.2,20,2)).position.set(0,4,3);stats.textContent=`${room.title} · time chamber`;msg.textContent='The clock has become architecture.'}
function buildTrainSource(room){const media=sourceShell(room,18,44,8,0x050505).filter(x=>x.type==='image'),c=room.config||{};box(-5,0,-7,7,.22,38,mats.stone,false);box(1,0,-7,2,.1,38,mats.dark,false);for(let z=-24;z<14;z+=2){box(1,.05,z,3,.12,.12,mats.wood,false)}const train=new THREE.Group();root.add(train);const cars=c.cars||6;for(let i=0;i<cars;i++){const car=box(1,1.5,-i*4,3,3.1,3.5,mats.dark,false,train);const it=media[i%Math.max(1,media.length)];if(it){const p=sourceImagePlane(it,2.2,1.6);p.position.set(0,1.6,-i*4+1.76);train.add(p)}}animated.push({object:train,speed:0,tick:()=>{train.position.z+=((c.trainSpeed||2.2)/60);if(train.position.z>20)train.position.z=-20}});addLight(new THREE.PointLight(0xffd28a,2,24,2)).position.set(-4,5,0);stats.textContent=`${room.title} · platform`;msg.textContent='Stand on the platform while the image train passes.'}
function buildAirplaneSource(room){const media=sourceShell(room,30,34,8,0x9bc9e8).filter(x=>x.type==='image'),c=room.config||{};box(0,.25,0,12,.5,18,mats.stone,true);const map=media[0];if(map){const p=sourceImagePlane(map,c.mapWidth||18,c.mapHeight||12);p.rotation.x=-Math.PI/2;p.position.set(0,.02,-5);root.add(p)}for(let i=0;i<10;i++){const seat=box((i%2?1:-1)*3,1,-6+Math.floor(i/2)*2.6,2,1.5,1.5,mats.dark,true)}addLight(new THREE.HemisphereLight(0xffffff,0x52718a,1.5));stats.textContent=`${room.title} · viewing deck`;msg.textContent='The airplane scene is now a suspended map-viewing cabin.'}
function buildLockedSource(room){sourceShell(room,24,24,10,0x020202);const c=room.config||{},rings=c.rings||7;for(let i=0;i<rings;i++){const r=2+i*1.15,t=new THREE.Mesh(new THREE.TorusGeometry(r,.08,8,80),i%2?mats.gold:mats.glow);t.rotation.x=Math.PI/2;t.position.y=4;root.add(t);animated.push({object:t,speed:(i%2?1:-1)*(c.spinSpeed||.08)*(1+i*.12)})}const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.1,1),mats.glow);core.position.y=4;root.add(core);clickObj(core,'Locked','The mechanism refuses to resolve.',()=>msg.textContent='Still locked. The geometry keeps turning.');addLight(new THREE.PointLight(0xffd06b,2.5,25,2)).position.set(0,4,2);stats.textContent=`${room.title} · vault mechanism`;msg.textContent='An endless lock occupies the chamber.'}
function buildSourceRoom(room){if(room.sourceScene==='dome')buildDomeSource(room);else if(room.sourceScene==='observatory')buildObservatorySource(room);else if(room.sourceScene==='books')buildBooksSource(room);else if(room.sourceScene==='objects')buildObjectsSource(room);else if(room.sourceScene==='clouds')buildCloudsSource(room);else if(room.sourceScene==='clock')buildClockSource(room);else if(room.sourceScene==='train')buildTrainSource(room);else if(room.sourceScene==='airplane')buildAirplaneSource(room);else buildLockedSource(room)}
JS;
$html = str_replace('function loadRoom(id){', $insert."\nfunction loadRoom(id){", $html);
$html = preg_replace("/else if\(r\.kind==='floorplan-gallery'\|\|r\.kind==='floorplan gallery'\)buildFloorplan\(r\);else msg\.textContent='No renderer for '\+r\.kind/", "else if(r.kind==='floorplan-gallery'||r.kind==='floorplan gallery')buildFloorplan(r);else if(r.kind==='source-scene-room')buildSourceRoom(r);else msg.textContent='No renderer for '+r.kind", $html, 1);
echo $html;
