<?php
ob_start();
require __DIR__ . '/index.php';
$html = ob_get_clean();

$mainJs = <<<'JS'
function buildMain(){
  reset();state.room='main';scene.background=new THREE.Color(0x070605);scene.fog=new THREE.FogExp2(0x070605,.012);setSpawn(cfg('mainSpawnX'),cfg('mainSpawnZ'),cfg('mainSpawnYaw'));
  box(0,-.06,0,44,.12,44,mats.floor,false);box(-22,5.5,0,.42,11,44,mats.wall);box(22,5.5,0,.42,11,44,mats.wall);box(0,5.5,-22,44,11,.42,mats.wall);box(0,5.5,22,44,11,.42,mats.wall);box(0,11,0,44,.12,44,mats.ceil,false);
  const dome=new THREE.Mesh(new THREE.SphereGeometry(22.8,48,20,0,Math.PI*2,0,Math.PI/2),mats.wall);dome.scale.y=.38;dome.position.y=10.9;root.add(dome);
  const altar=new THREE.Group();root.add(altar);cyl(0,.24,0,9.4,.48,mats.stone,true,altar);cyl(0,.56,0,8.3,.22,mats.gold,false,altar);cyl(0,.82,0,6.8,.3,mats.dark,false,altar);const altarRing=new THREE.Mesh(new THREE.TorusGeometry(7.6,.11,10,128),mats.gold);altarRing.rotation.x=Math.PI/2;altarRing.position.y=.98;altar.add(altarRing);
  const core=new THREE.Mesh(new THREE.IcosahedronGeometry(.82,1),mats.glow);core.position.y=1.82;altar.add(core);animated.push({object:core,speed:.32});
  function relicFor(r){
    const g=new THREE.Group(),s=r.sourceScene||r.id||'',k=r.kind||'';
    const add=m=>{g.add(m);return m};
    if(k==='art-history-room'){box(0,.35,0,1.65,.16,.45,mats.stone,false,g);box(-.64,.05,0,.14,.6,.45,mats.stone,false,g);box(.64,.05,0,.14,.6,.45,mats.stone,false,g)}
    else if(k==='hallway-gallery'){box(-.55,.8,0,.16,1.6,.16,mats.gold,false,g);box(.55,.8,0,.16,1.6,.16,mats.gold,false,g);box(0,1.55,0,1.26,.16,.16,mats.gold,false,g)}
    else if(k==='glass-tower'){add(new THREE.Mesh(new THREE.OctahedronGeometry(.78,0),mats.glass))}
    else if(k==='bar-room'){const b=add(new THREE.Mesh(new THREE.CylinderGeometry(.28,.42,1.45,24),new THREE.MeshPhysicalMaterial({color:0xb06b24,transparent:true,opacity:.68,roughness:.2})));b.position.y=.72;const n=add(new THREE.Mesh(new THREE.CylinderGeometry(.17,.2,.42,20),mats.gold));n.position.y=1.63}
    else if(k==='floorplan-gallery'||k==='floorplan gallery'){const m=add(new THREE.Mesh(new THREE.ConeGeometry(.78,1.45,4),new THREE.MeshStandardMaterial({color:0x7b2cff,emissive:0x2a005e,emissiveIntensity:.55})));m.position.y=.72}
    else if(s==='dome'){const m=add(new THREE.Mesh(new THREE.SphereGeometry(.9,24,12,0,Math.PI*2,0,Math.PI/2),mats.glow));m.scale.y=.65}
    else if(s==='observatory'){const star=add(new THREE.Mesh(new THREE.IcosahedronGeometry(.62,0),mats.glow));const orbit=add(new THREE.Mesh(new THREE.TorusGeometry(.92,.045,8,64),mats.gold));orbit.rotation.x=Math.PI/2;animated.push({object:orbit,speed:-.5})}
    else if(s==='books'){const book=add(new THREE.Mesh(new THREE.BoxGeometry(.9,1.3,.24),new THREE.MeshStandardMaterial({color:0x5c160f,roughness:.82})));book.position.y=.65;book.rotation.z=-.16;const spine=add(new THREE.Mesh(new THREE.BoxGeometry(.12,1.34,.28),mats.gold));spine.position.set(-.43,.65,0);spine.rotation.z=-.16}
    else if(s==='objects'){add(new THREE.Mesh(new THREE.TorusKnotGeometry(.5,.15,80,10),mats.glow))}
    else if(s==='clouds'){[[-.42,.55,0,.48],[.2,.72,0,.62],[.7,.48,0,.4]].forEach(v=>{const m=add(new THREE.Mesh(new THREE.SphereGeometry(v[3],16,12),mats.white));m.position.set(v[0],v[1],v[2])})}
    else if(s==='clock'){const ring=add(new THREE.Mesh(new THREE.TorusGeometry(.72,.09,10,64),mats.gold));const h=box(0,.32,.04,.08,.65,.08,mats.glow,false,g);h.rotation.z=-.55}
    else if(s==='train'){const axle=box(0,.55,0,1.5,.16,.16,mats.gold,false,g);[-.62,.62].forEach(x=>{const w=add(new THREE.Mesh(new THREE.TorusGeometry(.38,.11,10,36),mats.glow));w.position.set(x,.55,0);w.rotation.y=Math.PI/2})}
    else if(s==='airplane'){box(0,.6,0,.22,.22,1.55,mats.glow,false,g);box(0,.6,0,1.65,.08,.45,mats.gold,false,g);box(0,.6,.6,.75,.07,.34,mats.gold,false,g)}
    else if(s==='locked'){const body=box(0,.4,0,.95,.82,.28,mats.dark,false,g);const sh=add(new THREE.Mesh(new THREE.TorusGeometry(.4,.1,10,32,Math.PI),mats.gold));sh.position.y=.83;sh.rotation.z=Math.PI}
    else add(new THREE.Mesh(new THREE.TorusKnotGeometry(.5,.13,72,10),mats.glow));
    return g;
  }
  const rooms=sceneData.rooms||[],n=Math.max(rooms.length,1);rooms.forEach((r,i)=>{const a=i/n*Math.PI*2-Math.PI/2,rad=7.55,x=Math.cos(a)*rad,z=Math.sin(a)*rad,g=new THREE.Group();g.position.set(x,1.08,z);g.rotation.y=-a-Math.PI/2;altar.add(g);cyl(0,.12,0,.82,.24,mats.gold,false,g);const relic=relicFor(r);relic.position.y=.32;g.add(relic);const lab=labelSprite(r.title||r.id);lab.position.set(0,2.55,0);lab.scale.set(3.7,.92,1);g.add(lab);relic.traverse(o=>{if(o.isMesh)clickObj(o,r.title||r.id,r.description||'Enter room',()=>loadRoom(r.id))});animated.push({object:relic,speed:(i%2?-.22:.22)});colliders.push({x,z,w:1.5,d:1.5})});
  for(let i=0;i<10;i++){const a=i*Math.PI*2/10+Math.PI/10,x=Math.cos(a)*15.8,z=Math.sin(a)*15.8,g=new THREE.Group();g.position.set(x,0,z);root.add(g);cyl(0,3.6,0,.42,7.2,mats.stone,false,g);const orb=new THREE.Mesh(new THREE.SphereGeometry(.24,14,14),mats.glow);orb.position.y=7.5;g.add(orb);addLight(new THREE.PointLight(0xffd56d,.55,10,2)).position.set(x,7.5,z);colliders.push({x,z,w:1,d:1})}
  addLight(new THREE.HemisphereLight(0xf4dfb0,0x090705,.52));addLight(new THREE.PointLight(0xffd477,1.4,28,2)).position.set(0,8,0);stats.textContent=`Main altar · ${rooms.length} portals`;msg.textContent='The altar is live. Every relic is a room.';
}
JS;

$sourceJs = <<<'JS'
function sourceItems(room,type){return (sceneData.media?.[room.category]||[]).filter(i=>!type||i.type===type)}
function sourceReturn(x=0,z=7){const r=new THREE.Mesh(new THREE.OctahedronGeometry(.72,0),mats.glow);r.position.set(x,1.3,z);root.add(r);clickObj(r,'Return','Back to the altar.',buildMain);animated.push({object:r,speed:.72})}
function sourceShell(room,w=24,d=24,bg=0x050505,fog=.012){reset();state.room='source-'+(room.sourceScene||room.id);scene.background=new THREE.Color(bg);scene.fog=new THREE.FogExp2(bg,fog);setSpawn(room.spawn?.x??0,room.spawn?.z??8,room.spawn?.yaw??180);box(0,-.05,0,w,.1,d,mats.floor,false);sourceReturn(0,Math.min(d/2-2,7));return room.config||{}}
function planeFor(item,w=2.5,h=2){return new THREE.Mesh(new THREE.PlaneGeometry(w,h),item?new THREE.MeshBasicMaterial({map:tex(item.url),side:THREE.DoubleSide}):mats.dark)}
function fibonacciDir(i,n){const y=1-(i/(Math.max(1,n-1))),r=Math.sqrt(Math.max(0,1-y*y)),a=i*Math.PI*(3-Math.sqrt(5));return new THREE.Vector3(Math.cos(a)*r,y,Math.sin(a)*r)}
function buildDomeSource(room){const c=sourceShell(room,30,30,0x020205,.006),media=sourceItems(room,'image'),rad=c.radius||12,count=Math.min(media.length,c.maxImages||48);const shell=new THREE.Mesh(new THREE.SphereGeometry(rad+1.2,48,24,0,Math.PI*2,0,Math.PI/2),new THREE.MeshStandardMaterial({color:0x06060c,side:THREE.BackSide,roughness:1}));shell.position.y=.01;root.add(shell);for(let i=0;i<count;i++){const d=fibonacciDir(i,count),p=planeFor(media[i],c.imageWidth||2.3,c.imageHeight||1.75);p.position.set(d.x*rad,1.2+d.y*(rad-1),d.z*rad);p.lookAt(0,3.8,0);root.add(p)}const ring=new THREE.Mesh(new THREE.TorusGeometry(rad,.07,8,160),mats.gold);ring.rotation.x=Math.PI/2;ring.position.y=.08;root.add(ring);addLight(new THREE.HemisphereLight(0x7799cc,0x050508,.55));addLight(new THREE.PointLight(0xbfd9ff,c.lightIntensity||2.1,32,2)).position.set(0,6,0);stats.textContent=`${room.title} · ${count} works in the hemisphere`;msg.textContent='The Dome has become a walkable hemisphere of images.'}
async function buildObservatorySource(room){const c=sourceShell(room,30,30,0x010103,.0025),vectors=sourceItems(room,'vector'),rad=c.radius||12;const sky=new THREE.Mesh(new THREE.SphereGeometry(rad+1,32,20),new THREE.MeshBasicMaterial({color:0x010106,side:THREE.BackSide}));sky.position.y=4;root.add(sky);const starCount=Math.min(c.starCount||1200,1800);const pts=[];for(let i=0;i<starCount;i++){const a=Math.random()*Math.PI*2,y=1+Math.random()*10,r=5+Math.random()*8;pts.push(Math.sin(a)*r,y,Math.cos(a)*r)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));root.add(new THREE.Points(geo,new THREE.PointsMaterial({color:0xffffff,size:c.starSize||.045,transparent:true,opacity:.85})));if(vectors.length){try{const {SVGLoader}=await import('https://unpkg.com/three@0.161.0/examples/jsm/loaders/SVGLoader.js');const sl=new SVGLoader(),lim=Math.min(vectors.length,c.maxConstellations||18);vectors.slice(0,lim).forEach((it,i)=>sl.load(it.url,data=>{const grp=new THREE.Group();data.paths.forEach(path=>SVGLoader.createShapes(path).forEach(shape=>grp.add(new THREE.Mesh(new THREE.ShapeGeometry(shape),new THREE.MeshBasicMaterial({color:c.constellationColor||0x8c8c9c,side:THREE.DoubleSide,transparent:true,opacity:c.constellationOpacity||.62,depthWrite:false}))));const d=fibonacciDir(i,lim);grp.scale.setScalar(c.svgScale||.008);grp.position.set(d.x*10,2+d.y*7,d.z*10);grp.lookAt(0,4,0);root.add(grp)}))}catch(e){msg.textContent='The star field loaded. SVG constellation loader was unavailable.'}}addLight(new THREE.PointLight(0x6f88ff,.9,24,2)).position.set(0,5,0);stats.textContent=`${room.title} · ${vectors.length} constellation vectors`;msg.textContent='The observatory uses the original SVG constellation language inside a star vault.'}
function buildBooksSource(room){const c=sourceShell(room,24,28,0x171414,.008),books=sourceItems(room,'text'),n=Math.min(books.length,c.maxBooks||40),cols=c.columns||10,gap=c.shelfGap||1.75;box(0,4.4,-12.4,22,8.6,.42,mats.wood,true);for(let row=0;row<Math.ceil(n/cols);row++)box(0,1.1+row*gap,-11.92,21,.12,.72,mats.wood,false);const panel=new THREE.Group();panel.visible=false;root.add(panel);const board=box(0,3.2,-7.7,7,4.8,.16,mats.dark,false,panel);const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=700;const ctx=canvas.getContext('2d'),ct=new THREE.CanvasTexture(canvas),page=new THREE.Mesh(new THREE.PlaneGeometry(6.6,4.4),new THREE.MeshBasicMaterial({map:ct}));page.position.set(0,3.2,-7.6);panel.add(page);async function openBook(it){panel.visible=true;ctx.fillStyle='#eee7d7';ctx.fillRect(0,0,1024,700);ctx.fillStyle='#17120d';ctx.font='bold 40px Georgia';ctx.fillText(it.title.slice(0,38),50,65);ctx.font='27px Georgia';let text='';try{text=await (await fetch(it.url)).text()}catch(e){text='Unable to open this volume.'}const words=text.replace(/[#*_>`\[\]()]/g,' ').split(/\s+/);let line='',y=120;for(const word of words){const test=line+word+' ';if(ctx.measureText(test).width>920){ctx.fillText(line,50,y);line=word+' ';y+=38;if(y>650)break}else line=test}ctx.fillText(line,50,y);ct.needsUpdate=true;msg.textContent=`Opened ${it.title}.`}
  for(let i=0;i<n;i++){const row=Math.floor(i/cols),col=i%cols,w=.42+((i*17)%7)*.025,h=1+((i*11)%5)*.08,b=new THREE.Mesh(new THREE.BoxGeometry(w,h,.58),new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL((i*.073)%1,.42,.28),roughness:.82}));b.position.set((col-(cols-1)/2)*1.75,1.65+row*gap,-11.5);root.add(b);clickObj(b,books[i].title,'Open this volume.',()=>openBook(books[i]))}addLight(new THREE.HemisphereLight(0xffe5ba,0x160b08,.75));addLight(new THREE.PointLight(0xffb65a,2.2,24,2)).position.set(0,5,2);stats.textContent=`${room.title} · ${n} readable volumes`;msg.textContent='Click a book. The archive opens the actual text file.'}
async function buildObjectsSource(room){const c=sourceShell(room,28,28,0x0f0f10,.01),models=sourceItems(room,'model'),max=window.matchMedia('(pointer:coarse)').matches?Math.min(5,c.maxObjects||8):Math.min(10,c.maxObjects||10),items=models.slice(0,max),rad=c.radius||7;addLight(new THREE.HemisphereLight(0xffffff,0x202020,1.25));const spot=addLight(new THREE.SpotLight(0xffffff,c.lightIntensity||8,28,.55,.4,1.5));spot.position.set(4,8,5);try{const {GLTFLoader}=await import('https://unpkg.com/three@0.161.0/examples/jsm/loaders/GLTFLoader.js');const gl=new GLTFLoader();items.forEach((it,i)=>{const a=i/Math.max(1,items.length)*Math.PI*2,x=Math.sin(a)*rad,z=Math.cos(a)*rad;const pl=cyl(x,.45,z,.7,.9,mats.stone,true);gl.load(it.url,gltf=>{const obj=gltf.scene,box3=new THREE.Box3().setFromObject(obj),size=new THREE.Vector3();box3.getSize(size);const s=(c.objectScale||1.8)/Math.max(size.x,size.y,size.z,1e-4);obj.scale.setScalar(s);const b2=new THREE.Box3().setFromObject(obj),ctr=new THREE.Vector3();b2.getCenter(ctr);obj.position.set(x-ctr.x*s,1.0-b2.min.y,z-ctr.z*s);root.add(obj);obj.traverse(o=>{if(o.isMesh)clickObj(o,it.title,'A sculpture from the Objects archive.',()=>msg.textContent=it.title)})})})}catch(e){msg.textContent='The reliquary loaded, but the GLB loader was unavailable.'}stats.textContent=`${room.title} · ${items.length} sculpture reliquaries`;msg.textContent='The original GLB objects are becoming a circular reliquary.'}
function buildCloudsSource(room){const c=sourceShell(room,14,13,0x171717,.012),images=sourceItems(room,'image'),videos=sourceItems(room,'video');const plaid=document.createElement('canvas');plaid.width=plaid.height=256;const p=plaid.getContext('2d');p.fillStyle='#ecece8';p.fillRect(0,0,256,256);p.fillStyle='#202020';p.fillRect(0,82,256,20);p.fillRect(82,0,20,256);p.fillStyle='rgba(20,20,20,.2)';p.fillRect(0,170,256,14);p.fillRect(170,0,14,256);const pt=new THREE.CanvasTexture(plaid);pt.wrapS=pt.wrapT=THREE.RepeatWrapping;pt.repeat.set(2.2,1.35);const wall=new THREE.MeshStandardMaterial({map:pt,roughness:.95});box(0,4,-5.2,14,8,.25,wall,true);box(-7,4,.7,.25,8,13,mats.white,true);box(7,4,.7,.25,8,13,mats.white,true);box(0,8,.7,14,.18,13,mats.white,false);const ww=c.windowWidth||7.2,wh=c.windowHeight||4.05,wy=c.windowY||4.05,wz=-5.03;box(0,wy+wh/2+.18,wz,ww+.7,.28,.42,mats.wood,false);box(0,wy-wh/2-.18,wz,ww+.7,.28,.42,mats.wood,false);box(-ww/2-.18,wy,wz,.28,wh,.42,mats.wood,false);box(ww/2+.18,wy,wz,.28,wh,.42,mats.wood,false);let map=null;if(videos[0]){const v=document.createElement('video');v.src=videos[0].url;v.muted=true;v.loop=true;v.playsInline=true;v.crossOrigin='anonymous';v.play().catch(()=>{});roomAudio=v;map=new THREE.VideoTexture(v);map.colorSpace=THREE.SRGBColorSpace}else if(images[0])map=tex(images[0].url);const win=new THREE.Mesh(new THREE.PlaneGeometry(ww,wh),new THREE.MeshBasicMaterial({map,color:map?0xffffff:0x8cc3df}));win.position.set(0,wy,wz+.24);root.add(win);addLight(new THREE.HemisphereLight(0xf2f4ff,0x2d1d14,1.25));addLight(new THREE.PointLight(0xffc08a,3.2,16,2)).position.set(-4.8,5.6,2.2);stats.textContent=`${room.title} · ${videos.length} moving skies · ${images.length} still skies`;msg.textContent='The Clouds room keeps the original plaid room and impossible window.'}
function buildClockSource(room){const c=sourceShell(room,22,22,0x000000,.006),images=sourceItems(room,'image'),rad=c.radius||4.8;const face=new THREE.Mesh(new THREE.CylinderGeometry(rad,rad,.22,64),new THREE.MeshStandardMaterial({color:0xffffff,map:images[0]?tex(images[0].url):null,metalness:.2,roughness:.58}));face.position.y=.15;root.add(face);for(let i=0;i<12;i++){const a=i/12*Math.PI*2,t=box(Math.cos(a)*rad*.88,.32,Math.sin(a)*rad*.88,.12,.12,.55,mats.dark,false);t.rotation.y=-a}function hand(len,w,y,matl){const g=new THREE.Group();g.position.y=y;const h=box(0,0,len/2,w,.09,len,matl,false,g);root.add(g);return g}const hour=hand(rad*.48,.18,.39,mats.dark),minute=hand(rad*.72,.12,.44,mats.dark),second=hand(rad*.82,.06,.49,mats.gold);animated.push({object:{rotation:{y:0}},speed:0,tick:()=>{const d=new Date(),s=d.getSeconds()+d.getMilliseconds()/1000,m=d.getMinutes()+s/60,h=(d.getHours()%12)+m/60;second.rotation.y=-s*Math.PI*2/60;minute.rotation.y=-m*Math.PI*2/60;hour.rotation.y=-h*Math.PI*2/12}});addLight(new THREE.DirectionalLight(0xffffff,1.25)).position.set(5,10,5);stats.textContent=`${room.title} · live clock`;msg.textContent='The clock is floor-scale now, still driven by the real time.'}
function buildTrainSource(room){const c=sourceShell(room,20,56,0x5c5c5c,.012),imgs=sourceItems(room,'image'),cars=Math.max(3,Math.min(c.cars||8,12));box(-6,.1,-8,7,.2,50,mats.stone,false);for(let z=-30;z<20;z+=1.5){box(2,.08,z,4,.12,.14,mats.wood,false)}const train=new THREE.Group();root.add(train);for(let i=0;i<cars;i++){const z=-i*(c.carLength||4.4),car=box(2,1.6,z,c.carWidth||3.6,c.carHeight||3.2,(c.carLength||4.4)-.25,mats.dark,false,train);const it=imgs[i%Math.max(1,imgs.length)];if(it){const side=planeFor(it,2.8,1.9);side.position.set(-1.81,1.65,z);side.rotation.y=Math.PI/2;train.add(side)}}animated.push({object:{rotation:{y:0}},speed:0,tick:()=>{train.position.z+=(c.trainSpeed||2.2)/60;if(train.position.z>28)train.position.z=-18}});addLight(new THREE.HemisphereLight(0xffffff,0x222222,1));addLight(new THREE.PointLight(0xffd28a,1.8,26,2)).position.set(-4,5,0);stats.textContent=`${room.title} · ${cars} moving cars`;msg.textContent='The train keeps moving through the crypt platform.'}
async function buildAirplaneSource(room){const c=sourceShell(room,30,34,0x0b2b63,.01),models=sourceItems(room,'model'),images=sourceItems(room,'image'),mapItem=images.find(i=>/^map\./i.test(i.filename||''))||images[0];let floorTex=mapItem?tex(mapItem.url,2.2,6):null;const floor=new THREE.Mesh(new THREE.PlaneGeometry(c.mapWidth||22,c.mapHeight||38),new THREE.MeshBasicMaterial({map:floorTex,color:floorTex?0xffffff:0x194a7e,side:THREE.DoubleSide}));floor.rotation.x=-Math.PI/2;floor.position.y=.02;root.add(floor);if(floorTex)animated.push({object:{rotation:{y:0}},speed:0,tick:()=>{floorTex.offset.y+=(c.mapSpeed||.05)/60}});let loaded=false;if(models.length){try{const {GLTFLoader}=await import('https://unpkg.com/three@0.161.0/examples/jsm/loaders/GLTFLoader.js');new GLTFLoader().load(models[0].url,gltf=>{const plane=gltf.scene,b=new THREE.Box3().setFromObject(plane),s=new THREE.Vector3();b.getSize(s);plane.scale.setScalar((c.planeSize||4)/Math.max(s.x,s.y,s.z,1e-4));plane.position.set(0,3.4,0);plane.rotation.y=Math.PI*1.5;root.add(plane);animated.push({object:{rotation:{y:0}},speed:0,tick:()=>{plane.position.y=3.4+Math.sin(performance.now()*.001)*.08;plane.rotation.z=-.12+Math.sin(performance.now()*.0007)*.025}});loaded=true})}catch(e){}}if(!models.length){box(0,3.4,0,.35,.3,3.8,mats.glow,false);box(0,3.4,.1,5.2,.12,1.0,mats.gold,false)}addLight(new THREE.HemisphereLight(0xffffff,0x173458,1.3));addLight(new THREE.DirectionalLight(0xffffff,1.2)).position.set(4,9,6);stats.textContent=`${room.title} · surreal flight chamber`;msg.textContent='The airplane floats over the scrolling map, preserving the original journey illusion.'}
function buildLockedSource(room){const c=sourceShell(room,30,30,0x000000,.015),imgs=sourceItems(room,'image'),count=Math.min(c.planeCount||90,120);for(let i=0;i<count;i++){const a=(i*2.399963)% (Math.PI*2),r=2+(i%18)*.68,y=.8+((i*7)%13)*.55,it=imgs.length?imgs[i%imgs.length]:null,p=planeFor(it,.8+(i%5)*.22,.8+(i%5)*.22);p.position.set(Math.cos(a)*r,y,Math.sin(a)*r);p.rotation.set((i%7)*.13,a+Math.PI,(i%5)*.09);root.add(p)}const rings=c.rings||5;for(let i=0;i<rings;i++){const t=new THREE.Mesh(new THREE.TorusGeometry(1.8+i*.65,.06,8,64),i%2?mats.gold:mats.glow);t.position.y=4;t.rotation.x=Math.PI/2;root.add(t);animated.push({object:t,speed:(i%2?1:-1)*(c.spinSpeed||.12)})}addLight(new THREE.PointLight(0xffcf67,1.5,20,2)).position.set(0,4,0);stats.textContent=`${room.title} · infinite vault`;msg.textContent='LOCKED becomes an infinite field around a mechanism that never resolves.'}
function buildSourceRoom(room){const s=room.sourceScene;if(s==='dome')return buildDomeSource(room);if(s==='observatory')return buildObservatorySource(room);if(s==='books')return buildBooksSource(room);if(s==='objects')return buildObjectsSource(room);if(s==='clouds')return buildCloudsSource(room);if(s==='clock')return buildClockSource(room);if(s==='train')return buildTrainSource(room);if(s==='airplane')return buildAirplaneSource(room);return buildLockedSource(room)}
JS;

$html = preg_replace_callback('/function buildMain\(\)\{.*?\}\nfunction buildHallway\(room\)\{/s', fn($m) => $mainJs . "\nfunction buildHallway(room){", $html, 1);
$html = str_replace('function loadRoom(id){', $sourceJs . "\nfunction loadRoom(id){", $html);
$html = preg_replace("/else\s+msg\.textContent='No renderer for '\+r\.kind\}/", "else if(r.kind==='source-scene-room')buildSourceRoom(r);else msg.textContent='No renderer for '+r.kind}", $html, 1);

echo $html;
